### ISSUE TITLE
攻撃時に攻撃方向に移動するようにする

### ISSUE THREAD

**Issue by ichiharayuuma** [Twilight-Studioo/production#117]
Lスティックの入力方向に移動（攻撃方向と同じ）
プレイヤーを回転させて不自然さがないか実験もしてほしいです

**Comment by ichiharayuuma** [comment]
上下（重力方向）も含めた入力方向です
なので斜め上に入力しながら攻撃したら斜め上に移動する感じです

**Comment by Matuyuhi** [comment]
上ってことはジャンプするってことですか？それとも上にも歩ける？
前後にしか動けないものと思ってました

**Comment by ichiharayuuma** [comment]
こんなイメージです

https://github.com/user-attachments/assets/c2494317-7726-4e62-9e1b-35e03ef3d0d8

**Comment by Matuyuhi** [comment]
分かりました。今の実装の修正が必要だと思います

**Comment by Matuyuhi** [comment]
着手
多分イメージはホロウナイト

**Comment by Matuyuhi** [comment]
[ここ](https://github.com/Twilight-Studioo/production/pull/154)で実装

**Comment by ichiharayuuma** [comment]
イメージに関しては Katana Zero が近いです。
空中での横方向の移動量だけ多いのが気になります

**Comment by Matuyuhi** [comment]
空中の移動量が2倍になっていたので修正
