### ISSUE TITLE
地面の下、壁の中にスワップしないようにする

### ISSUE THREAD

**Issue by ichiharayuuma** [Twilight-Studioo/production#141]

**Comment by Hayato222** [comment]
@ichiharayuuma 
最新版にすると今まで起きていた敵と近距離でスワップしたときに発生する床抜けバグが自分が確認した限りでは起きなくなりました。
僕の環境だけかもしれないので一応チェックお願いしたいです。

**Comment by ichiharayuuma** [comment]
ゆうひ君が直してくれたぽいです
