### ISSUE TITLE
スワップ専用カメラの実装

### ISSUE THREAD

**Issue by Hayato222** [Twilight-Studioo/production#168]
スワップ範囲がすべて映る程度に引いたカメラ
スワップ中はそのカメラに切り替え
シネマシーンのVirtualCameraを使用

**Comment by ichiharayuuma** [comment]
@Hayato222 
close しますが、
- カメラの位置の調整方法
- 遷移の速度の調整方法
を教えてほしいです

**Comment by ichiharayuuma** [comment]
嘘です、レビューの内容直してください

**Comment by Matuyuhi** [comment]
済
