### ISSUE TITLE
スタミナの実装

### ISSUE THREAD

**Issue by ichiharayuuma** [Twilight-Studioo/production#17]
スワップによって消費されるスタミナの実装
スタミナが0になった場合（0を下回る場合）スワップはキャンセルされる

**Comment by Matuyuhi** [comment]
スワップがキャンセルというのはそもそもスワップ状態に入れないということですか？それとも一瞬時間がゆっくりになるみたいな

**Comment by ichiharayuuma** [comment]
現状スタミナが減るタイミングを決め切れていないのが悪いのですが、
スワップモード中に継続的に減らすとするとモード中に0になってしまったり、
スワップ実行時に減らすとするとモードには入れてもスワップできないという状況になってしまう可能性があります。

なのでスタミナを減らすタイミングで0を下回ったときにその行動をキャンセルするようにしてください。
その時にシグナルとして被ダメージのモーションをするつもりです（今はいらないです）。

**Comment by Matuyuhi** [comment]
了解です。
適当に0になった時のイベントだけ受け取れるようにしておきます
