### ISSUE TITLE
回転刃の実装

### ISSUE THREAD

**Issue by ichiharayuuma** [Twilight-Studioo/production#182]
回転部分と当たるとプレイヤーも敵もダメージ
普段は指定されたポイントを行ったり来たりする（レール上）

--- ここからできたら ---
回転部分とスワップ可能
レールから外れると回転に従って移動
壁などにあたるまで動く

**Comment by ichiharayuuma** [comment]
どのくらいできましたか

**Comment by ichiharayuuma** [comment]
@Hayato222 
見たところダメージがなさそうです

**Comment by ichiharayuuma** [comment]
@Hayato222 
確認しました
いい感じだと思います！

Rigidbody の freeze position でZ軸の動きをなくすのと、
レールから外れたら一定時間後に刃は消えてレール上にリポップするようにしてほしいです。（ここは別issueでも〇）

**Comment by Hayato222** [comment]
@ichiharayuuma
way pointは親子関係にしてしまうと刃が動いたときに一緒に動いちゃうので入れられないです。
リポップの処理は別issueにしてここまででいったんプルリクしても大丈夫ですか？

**Comment by ichiharayuuma** [comment]
プルリクOKです

empty object の下に saw と way point をいれれば大丈夫だと思います。

**Comment by ichiharayuuma** [comment]
#210 に引継ぎ
