### ISSUE TITLE
カメラの注視点をプレイヤーの前にする

### ISSUE THREAD

**Issue by ichiharayuuma** [Twilight-Studioo/production#187]
![Image](https://github.com/user-attachments/assets/ea221b11-9517-4b80-9932-0af3789677f1)

上の図の感じでプレイヤーの前方にある点をカメラが追うようにしたいです。
できたら移動しているかどうかでプレイヤーと注視点の距離を変えたい

**Comment by Matuyuhi** [comment]
移動中と止まっている時の2パターンで、中視点用意しておけば良いですか？
その前に今は敵がいると敵も含めた中心辺りにカメラが動くようになってますがどうしますか？(targetgroupなんとかで)

**Comment by ichiharayuuma** [comment]
targetgroup の機能はほしいです。
その時もプレイヤーに関しては同じ注視点を使う感じにしたいです。

**Comment by ichiharayuuma** [comment]
ついでに #191 もいいですか…
