### ISSUE TITLE
スワップアイテムのスポーンポイントの追加

### ISSUE THREAD

**Issue by ichiharayuuma** [Twilight-Studioo/production#189]
スワップアイテムを生み出す点

- 1度に生み出す数
- 何秒ごとに生み出すか（floatがいいかもです）

**Comment by Matuyuhi** [comment]
スワップアイテムって宙に浮いてるので1点にスポーンすると重なっていきますけど大丈夫ですか？

**Comment by Matuyuhi** [comment]
マージされてる

**Comment by Matuyuhi** [comment]
プレイヤーとの距離見てスポーン開始も入ったので完了で
