### ISSUE TITLE
エネミーを飛べるようにする

### ISSUE THREAD

**Issue by ichiharayuuma** [Twilight-Studioo/production#192]

**Comment by Matuyuhi** [comment]
navmeshの移動では飛ぶことはできないと思います。
bake設定で指定heightの段差を無視するような設定はあります

**Comment by ichiharayuuma** [comment]
空中を飛べるようにしてほしいです

**Comment by Matuyuhi** [comment]
飛ぶってジャンプする事だと思ってましたけど、今のドローンの動き的な話ですか？

**Comment by ichiharayuuma** [comment]
そうです

**Comment by Matuyuhi** [comment]
既存の雑魚敵の仕様のまま？でドローンのように空を飛ぶバージョンがいた方が楽しそうってことでした
具体的に仕様待ちで

**Comment by ichiharayuuma** [comment]
https://youtu.be/4EN-JjdXNzg?t=1405
この辺の飛んでる敵のイメージです

**Comment by Matuyuhi** [comment]
これは今のドローンではダメってことですか？

**Comment by ichiharayuuma** [comment]
大丈夫です
雑魚敵も同じ動きにするか選べるようにしてほしいです

今の動きだとコンベア上でnavmeshが生成されなくて思った動きにならないです

**Comment by Matuyuhi** [comment]
その理由であれば、コンベアの動きを修正した方が良いと思いますがどうですか？

**Comment by ichiharayuuma** [comment]
コンベアを修正したうえで今の動きと飛んでる動きから選べるようにしたいです

**Comment by Matuyuhi** [comment]
コンベア修正するなら、飛ぶ必要ってありますか？
見た目が気になるなら、モデルだけ飛んでるものに差し替えれば良いと思います

**Comment by ichiharayuuma** [comment]
空中を移動して攻撃してくる敵が欲しいので飛ぶ雑魚敵もほしいです

**Comment by Matuyuhi** [comment]
着手

**Comment by Matuyuhi** [comment]
動画の動きに割と近づいたので終わります

**Comment by Matuyuhi** [comment]
SimpleEnemy2Flyが追加されました
