### ISSUE TITLE
敵との距離に応じてカメラの距離を変える

### ISSUE THREAD

**Issue by ichiharayuuma** [Twilight-Studioo/production#194]
targetgroup に入ってる敵とプレイヤーが画面内に納まるようにしたいです

**Comment by Matuyuhi** [comment]
画面に映すべきobj座標の最大値最小値を取得して、それに合わせてカメラのzを調節すれば良い
が、制限をかけないとどんどん小さくなってしまうので注意

**Comment by ichiharayuuma** [comment]
なるほどです
targetgroup の中のものを全部納まるようにはできますか？

**Comment by Matuyuhi** [comment]
今のtargetgroupはobjたちの中心に位置を決めてるだけな気がするので、
恐らくそこから手動で、カメラのzを前後させるようにすればできると思います

**Comment by Matuyuhi** [comment]
@shibatosora が10/16以降やる予定
