### ISSUE TITLE
回転刃の動きの修正

### ISSUE THREAD

**Issue by ichiharayuuma** [Twilight-Studioo/production#211]
プレイヤーにあたったときレーンから離れてしまっていました。
スワップされるまでは何と当たってもレーンから離れないでほしいです。

また、動画のようにプレイヤーが移動上にいるときに避けて移動してしまっていました。
https://github.com/user-attachments/assets/fca938fe-9af9-472b-bcc9-0dbe3b15f543

**Comment by Matuyuhi** [comment]
すでに修正されている気がします
