### ISSUE TITLE
スワップモード中は直前の動きを続ける

### ISSUE THREAD

**Issue by ichiharayuuma** [Twilight-Studioo/production#291]
スワップモードに入ると移動が止まってしまって煩わしいので

**Comment by Matuyuhi** [comment]
攻撃とかのモーションも含めてですか？
だいぶ大変そうです

**Comment by ichiharayuuma** [comment]
見た感じ、モーションはスワップモードに入っても最後まで再生されているので移動だけで大丈夫そうです
