### ISSUE TITLE
ダメージエフェクトの実装

### ISSUE THREAD

**Issue by ichiharayuuma** [Twilight-Studioo/production#294]
敵用、主人公用2種類用意してあります

**Comment by Matuyuhi** [comment]
敵とplayerそれぞれどのファイルですか？

**Comment by Matuyuhi** [comment]
@ichiharayuuma or 誰か

**Comment by ichiharayuuma** [comment]
Contents/VFX/Damage_effect の下にプレイヤーとエネミー用のエフェクトがあります
お願いします
