### ISSUE TITLE
ヒットストップの実装

### ISSUE THREAD

**Issue by ichiharayuuma** [Twilight-Studioo/production#295]
主人公の攻撃があたったとき

**Comment by Matuyuhi** [comment]
ヒットストップという現象についてあまり知らないです。検索したら、
> ゲーム内の格闘やアクションにおいて、攻撃が相手にヒットしたときに、プログラム上で意図的に次の動作を遅らせること

らしいのですが、これは敵の話ですか？
あと↑は合ってますか？

**Comment by ichiharayuuma** [comment]
ヒットストップあってます

主人公が敵を攻撃し、当たったときにヒットストップが起こります
