### ISSUE TITLE
スワップアイテムに乗れるようにする

### ISSUE THREAD

**Issue by ichiharayuuma** [Twilight-Studioo/production#353]
ボックス型のアイテムなどに乗ったときに着地してジャンプできるようにする

**Comment by Matuyuhi** [comment]
修正しました。
今後swapItemは`SwapItemTag`というscriptをつけてください。(Prefabs/SwapItemにあるものは付けました)
基本は`Untagged`にして、着地できるもののみ、`Ground`タブをつけて下さい。
